name: Patient Order CI/CD

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: us-east-1
  ECR_REPOSITORY: patient-order
  AWS_ACCOUNT_ID: "340375561601"

jobs:

  validate:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          pip install -r app/requirements.txt

      - name: Validate Python
        run: |
          python -m py_compile app/app.py

      - name: Build Docker image
        run: |
          docker build -t patient-order:test ./app

      - name: Test Docker image
        run: |
          docker run -d \
            --name patient-order-test \
            -p 5000:5000 \
            patient-order:test

          sleep 5

          curl --fail http://localhost:5000/health

          docker stop patient-order-test

  push-to-ecr:

    needs: validate

    if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    runs-on: ubuntu-latest

    steps:

      - name: Checkout code
        uses: actions/checkout@v4
      - name: Debug OIDC token
        run: |
          TOKEN=$(curl -sSL -H "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" "$ACTIONS_ID_TOKEN_REQUEST_URL&audience=sts.amazonaws.com" | jq -r '.value')
          echo "$TOKEN" | cut -d. -f2 | base64 -d 2>/dev/null | jq .
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v6
        with:
          role-to-assume: ${{ vars.AWS_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Verify AWS identity
        run: |
          aws sts get-caller-identity

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build Docker image
        run: |
          docker build \
            -t $ECR_REPOSITORY:${GITHUB_SHA} \
            ./app

      - name: Tag Docker image
        run: |
          docker tag \
            $ECR_REPOSITORY:${GITHUB_SHA} \
            $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPOSITORY:${GITHUB_SHA}

      - name: Push Docker image to ECR
        run: |
          docker push \
            $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPOSITORY:${GITHUB_SHA}
